
from typing import Protocol, runtime_checkable


@runtime_checkable
class ConversationRepositoryPort(Protocol):
    def get_conversation_with_user_check(self, conversation_id: str, user_id: str, only_active: bool = True): ...
    def get_user_conversation_summaries(self, user_id: str, limit: int, offset: int, only_active: bool = True): ...
    def count_user_conversations(self, user_id: str, only_active: bool = True) -> int: ...
    def create_conversation(self, conversation_create): ...
    def update_message_count(self, conversation_id: str, increment: int = 1) -> bool: ...
    def update_conversation_timestamp(self, conversation_id: str) -> bool: ...
    def update_conversation(self, conversation_id: str, conversation_update) -> bool: ...
    def delete_conversation(self, conversation_id: str, soft_delete: bool = True) -> bool: ...

