"""File repository protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class FileRepositoryPort(Protocol):
    def create_file(self, file_create): ...
    def get_file_by_id(self, file_id: str): ...
    def get_files_by_user_id(self, user_id: str, limit: int | None = None, offset: int | None = None): ...
    def delete_file(self, file_id: str) -> bool: ...

