
from typing import Protocol, runtime_checkable


@runtime_checkable
class KnowledgeBaseRepositoryPort(Protocol):
    def list_by_user(self, user_id: str, active_only: bool = True): ...
    def create_knowledge_base(self, knowledge_base_create): ...
    def get_by_id_for_user(self, knowledge_base_id: str, user_id: str): ...
    def get_default_by_user(self, user_id: str): ...
    def exists_by_name(self, user_id: str, name: str) -> bool: ...
    def clear_default(self, user_id: str) -> int: ...
    def set_default_by_id(self, knowledge_base_id: str, user_id: str) -> bool: ...
    def soft_delete_knowledge_base(self, knowledge_base_id: str, user_id: str) -> bool: ...
