"""Message repository protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class MessageRepositoryPort(Protocol):
    def get_conversation_history(self, conversation_id: str, limit: int | None = None): ...
    def get_next_sequence_number(self, conversation_id: str) -> int: ...
    def create_message(self, message_create): ...
    def get_messages_by_conversation_id(self, conversation_id: str, limit: int | None = None, offset: int | None = None): ...
    def count_messages_by_conversation_id(self, conversation_id: str) -> int: ...

