
from typing import Protocol, runtime_checkable


@runtime_checkable
class UserRepositoryPort(Protocol):
    def create_user(self, user): ...
    def get_user_by_id(self, user_id: str): ...
    def get_user_by_username(self, username: str): ...
    def get_user_by_email(self, email: str): ...
    def exists_by_username(self, username: str) -> bool: ...
    def exists_by_email(self, email: str) -> bool: ...
    def update_last_login(self, user_id: str) -> bool: ...
