
from typing import Protocol, runtime_checkable


@runtime_checkable
class FileStorageGatewayPort(Protocol):
    def build_path(self, upload_dir: str, file_id: str, original_filename: str) -> str: ...
    def write_bytes(self, path: str, content: bytes) -> None: ...
    def delete(self, path: str) -> None: ...
    def exists(self, path: str) -> bool: ...
